config/routes.rb
Followme::Application.routes.draw do
  
  get "mobile/mail"

  get "mobile/activate"

  get "mobile/signal"

  get "mobile/check"

  match 'lieus/check' => 'lieus#check'
  
  resources :balises
  resources :lieus

    

   root :to => "welcome#index"

end

app/models/balise.rb
class Balise < ActiveRecord::Base
    attr_accessible :code
    has_many :lieus
    before_save :create_unique_identifier

    def create_unique_identifier
        self.code = rand(36**8).to_s(36)
    end
end

app/models/lieu.rb
class Lieu < ActiveRecord::Base
  belongs_to :balise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/balises_controller.rb
class BalisesController < ApplicationController
  
  
  def index
    @balises = Balise.all
  end

  def show
    @balise = Balise.find(params[:id])
  end

  def new
    @balise = Balise.new
  end

  def create
    @balise = Balise.new(params[:balise])
    if @balise.save
      flash[:notice] = "Successfully created balise."
      redirect_to @balise
    else
      render :action => 'new'
    end
  end

  def edit
    @balise = Balise.find(params[:id])
  end

  def update
    @balise = Balise.find(params[:id])
    if @balise.update_attributes(params[:balise])
      flash[:notice] = "Successfully updated balise."
      redirect_to balise_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @balise = Balise.find(params[:id])
    @balise.destroy
    flash[:notice] = "Successfully destroyed balise."
    redirect_to balises_url
  end
end

app/controllers/lieus_controller.rb
class LieusController < ApplicationController

  #depuis le web
  def check
    @code = params[:code]
    @lieus = Balise.find_by_code(@code).lieus
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lieus }
    end
  end

  # GET /lieus
  # GET /lieus.xml
  def index
    @lieus = Lieu.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lieus }
    end
  end

  # GET /lieus/1
  # GET /lieus/1.xml
  def show
    @lieu = Lieu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lieu }
    end
  end

  # GET /lieus/new
  # GET /lieus/new.xml
  def new
    @lieu = Lieu.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lieu }
    end
  end

  # GET /lieus/1/edit
  def edit
    @lieu = Lieu.find(params[:id])
  end

  # POST /lieus
  # POST /lieus.xml
  def create
    @lieu = Lieu.new(params[:lieu])

    respond_to do |format|
      if @lieu.save
        format.html { redirect_to(@lieu, :notice => 'Lieu was successfully created.') }
        format.xml  { render :xml => @lieu, :status => :created, :location => @lieu }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lieu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lieus/1
  # PUT /lieus/1.xml
  def update
    @lieu = Lieu.find(params[:id])

    respond_to do |format|
      if @lieu.update_attributes(params[:lieu])
        format.html { redirect_to(@lieu, :notice => 'Lieu was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lieu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lieus/1
  # DELETE /lieus/1.xml
  def destroy
    @lieu = Lieu.find(params[:id])
    @lieu.destroy

    respond_to do |format|
      format.html { redirect_to(lieus_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  
  def mail
    @code = params[:code]
  end
  
  
  def check
    @code = params[:code]
    @lieus = Balise.find_by_code(@code).lieus
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lieus }
    end
  end
  
  
  def activate
    @balise=Balise.new
    @balise.save!
    respond_to do |format|
      format.xml { render :xml => @balise }
    end
  end

  def signal
    @balise = Balise.find_by_code(params[:code])
    @lieu = Lieu.new
    @lieu.balise_id = @balise.id
    @lieu.lng =  params[:lng]
    @lieu.lat =  params[:lat]
    @lieu.save!
    respond_to do |format|
      format.xml { render :xml => @lieu}
    end
  end

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/balises_helper.rb
module BalisesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/lieus_helper.rb
module LieusHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/balises/_form.html.erb
<%= form_for @balise do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/balises/edit.html.erb
<% title "Edit Balise" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @balise %> |
  <%= link_to "View All", balises_path %>
</p>

app/views/balises/index.html.erb
<% title "Balises" %>

<table>
  <tr>
    <th>Code</th>
  </tr>
  <% for balise in @balises %>
    <tr>
      <td><%= balise.code %>(<%=balise.lieus.length%>)</td>
      <td><%= link_to "Show", balise %></td>
      <td><%= link_to "Edit", edit_balise_path(balise) %></td>
      <td><%= link_to "Destroy", balise, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Balise", new_balise_path(balise) %></p>

app/views/balises/new.html.erb
<% title "New Balise" %>

<%= render 'form' %>

<p><%= link_to "Back to List", balises_path %></p>

app/views/balises/show.html.erb
<% title "Balise" %>

<p>
  <strong>Code:</strong>
  <%= @balise.code %>
  <strong>Lieus:</strong>
  (<%= @balise.lieus.length %>)
</p>

<p>
  <%= link_to "Edit", edit_balise_path(@balise) %> |
  <%= link_to "Destroy", @balise, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", balises_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "" %></title>
    <%= stylesheet_link_tag "master","login" %>
    <%= javascript_include_tag :all %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
   <body onload="initialize()">
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lieus/_form.html.erb
<%= form_for(@lieu) do |f| %>
  <% if @lieu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lieu.errors.count, "error") %> prohibited this lieu from being saved:</h2>

      <ul>
      <% @lieu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lieus/_map.html.erb
<%= content_for :head do%>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
 
<script type="text/javascript">
 

function display(){
		<% @lieus.each do |lieu| %> 
        var m = map.addMarker(<%=lieu.lat%>,<%=lieu.lng%>);
	  	map.addWindow(m,"<%=lieu.created_at%>");
	  <%end%>
	}

function initialize(){
	 
	  map = new CMap();
      map.create('map',<%=@lieus[0].lat%>,<%=@lieus[0].lng%>);   
      display();
	  map.detectBrowser('map');
	  setTimeout("display();",15000);
	}      
</script>
<%end%>

app/views/lieus/_map.old.html.erb
<%= content_for :head do%>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
 
<script type="text/javascript">
      <%=raw initialize_map(@lieus) unless @lieus.nil? or @lieus.empty?%>              
</script>
<%end%>

app/views/lieus/check.html.erb
<%=render :partial=>'lieus/map'%>
<div>Il faudra mettre de la pub ici , il y a <%=@lieus.length%> lieus</div>
<div id="map"></div>  

app/views/lieus/edit.html.erb
<h1>Editing lieu</h1>

<%= render 'form' %>

<%= link_to 'Show', @lieu %> |
<%= link_to 'Back', lieus_path %>

app/views/lieus/index.html.erb
<h1>Listing lieus</h1>

<table>
  <tr>
    <th>Lat</th>
    <th>Lng</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lieus.each do |lieu| %>
  <tr>
    <td><%= lieu.lat %></td>
    <td><%= lieu.lng %></td>
    <td><%= link_to 'Show', lieu %></td>
    <td><%= link_to 'Edit', edit_lieu_path(lieu) %></td>
    <td><%= link_to 'Destroy', lieu, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lieu', new_lieu_path %>

app/views/lieus/new.html.erb
<h1>New lieu</h1>

<%= render 'form' %>

<%= link_to 'Back', lieus_path %>

app/views/lieus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lat:</b>
  <%= @lieu.lat %>
</p>

<p>
  <b>Lng:</b>
  <%= @lieu.lng %>
</p>


<%= link_to 'Edit', edit_lieu_path(@lieu) %> |
<%= link_to 'Back', lieus_path %>

app/views/mobile/check.html.erb
<%unless @lieus.empty? or @lieus.nil? %>
<%=render :partial=>'lieus/map'%>
<div id="map"></div> 
<%else%>
Aucune position enregistrée 
<%end%>

app/views/mobile/mail.html.erb
<b> Bonjour </b>
<p> tu peux suivre mon trajet sur http://suismoi.heroku.com en entrant le code suivant : <%=@code%></p>
<p> ou si tu preferes en cliquant directement sur ce lien <a href="http://suismoi.heroku.com/lieus/check?code=<%=@code%>">Suis Moi</a> </p>

app/views/welcome/index.html.erb
<div id="full" class="" >
<div id="log_container" class="" >


<div class="logbox">
  <h2>Entrer le Code de la personne à suivre</h2>

<%= form_tag(url_for(:controller=>"lieus",:action=>"check"), :method => "get", :id=>"pass", :class=>"form-password") do %>
  <%= text_field_tag(:code) %>
  <%= submit_tag("Entrer") %>
<% end %>
</div>

</div>
</div>